package perfume_pins;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller
@RequestMapping(path = "/account")
public class UserController {
    @Autowired
    /*
    This gets the bean userRepository.(This is auto generated by spring and also
    handles the data.
     */
    private UserRepository userRepository;


    @GetMapping(path = "/create")
    public @ResponseBody String createNewUser(
            @RequestParam String firstName,
            @RequestParam String lastName,
            @RequestParam String userName,
            @RequestParam String userPassword,
            @RequestParam String userEmail

    ){
        User myAccount = new User();
        myAccount.setFirstName(firstName);
        myAccount.setLastName(lastName);
        myAccount.setUserName(userName);
        myAccount.setUserPassword(userPassword);
        myAccount.setUserEmail(userEmail);
        userRepository.save(myAccount);
        return "Welcome to Perfume Pin Trader " +
                myAccount.getFirstName() + " " +
                myAccount.getLastName() + "!";
    }


    @GetMapping(path = "/myaccount/myinfo")
    public @ResponseBody String getMyAccountInfo(
            @RequestParam int userId
    ){
        return userRepository.findById(userId);


        };

    }




}
